// <auto-generated />
using System;
using FootballClubLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballClubLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230327160253_FinalMigration")]
    partial class FinalMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballClubLibrary.Models.Klub", b =>
                {
                    b.Property<Guid>("IdKlub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stadion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Trofea")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKlub");

                    b.ToTable("Kluby");

                    b.HasData(
                        new
                        {
                            IdKlub = new Guid("d8846ec1-c8ce-43fd-87e0-f6ca49f0d10e"),
                            Nazwa = "Klub1",
                            Stadion = "Stadion1"
                        },
                        new
                        {
                            IdKlub = new Guid("97639ccf-13a1-4f8a-b405-5f1a4482191f"),
                            Nazwa = "Klub2",
                            Stadion = "Stadion2"
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pilkarz", b =>
                {
                    b.Property<Guid>("IdPilkarz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKlubu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pozycja")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Wynagrodzenie")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPilkarz");

                    b.HasIndex("IdKlubu");

                    b.ToTable("Pilkarze");

                    b.HasData(
                        new
                        {
                            IdPilkarz = new Guid("aa2811a8-fb02-4841-bc83-84ec98114a60"),
                            Pozycja = "Napastnik",
                            Wynagrodzenie = 1000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("b6e0ad33-c448-4c7d-bea0-7a4643943ea4"),
                            Pozycja = "Pomocnik",
                            Wynagrodzenie = 2000m
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pracownik", b =>
                {
                    b.Property<Guid>("IdPracownik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdZarzadu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imie")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nazwisko")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PESEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wiek")
                        .HasColumnType("int");

                    b.Property<string>("WykonywanaFunkcja")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Wynagrodzenie")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPracownik");

                    b.HasIndex("IdZarzadu");

                    b.ToTable("Pracownicy");

                    b.HasData(
                        new
                        {
                            IdPracownik = new Guid("026a7c74-82ae-4b24-8ae9-ff948adcba90"),
                            Imie = "Mateusz",
                            Nazwisko = "Kostyra",
                            PESEL = "00124168751",
                            Wiek = 23,
                            WykonywanaFunkcja = "Prezes",
                            Wynagrodzenie = 50000m
                        },
                        new
                        {
                            IdPracownik = new Guid("ea7c1f63-805e-451d-9686-b469f31e7c06"),
                            Imie = "Stanisław",
                            Nazwisko = "Kluczewski",
                            PESEL = "00864164771",
                            Wiek = 23,
                            WykonywanaFunkcja = "Vc-Prezes",
                            Wynagrodzenie = 50000m
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Statystyka", b =>
                {
                    b.Property<Guid>("IdStatystyka")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Asysty")
                        .HasColumnType("int");

                    b.Property<int>("CzerwoneKartki")
                        .HasColumnType("int");

                    b.Property<int>("Gole")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdPilkarz")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mecz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ocena")
                        .HasColumnType("float");

                    b.Property<double>("PrzebiegnietyDystans")
                        .HasColumnType("float");

                    b.Property<int>("ZolteKartki")
                        .HasColumnType("int");

                    b.HasKey("IdStatystyka");

                    b.HasIndex("IdPilkarz");

                    b.ToTable("Statystki");

                    b.HasData(
                        new
                        {
                            IdStatystyka = new Guid("21e6caf1-1184-4802-82c6-ecd02b5fc985"),
                            Asysty = 1,
                            CzerwoneKartki = 1,
                            Gole = 4,
                            Ocena = 8.6999999999999993,
                            PrzebiegnietyDystans = 10.4,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("77afdb37-3517-4db1-9e33-82b1d2164f27"),
                            Asysty = 2,
                            CzerwoneKartki = 1,
                            Gole = 0,
                            Ocena = 7.5,
                            PrzebiegnietyDystans = 8.4000000000000004,
                            ZolteKartki = 2
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Zarzad", b =>
                {
                    b.Property<Guid>("IdZarzad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Budzet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cele")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdKlubu")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdZarzad");

                    b.HasIndex("IdKlubu")
                        .IsUnique()
                        .HasFilter("[IdKlubu] IS NOT NULL");

                    b.ToTable("Zarzady");

                    b.HasData(
                        new
                        {
                            IdZarzad = new Guid("4cb42210-e7ab-4ca1-87b2-ae6b3db9e3a2"),
                            Budzet = 2000m
                        });
                });

            modelBuilder.Entity("KlubPilkarz", b =>
                {
                    b.Property<Guid>("ArchiwalneKlubyIdKlub")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArchwilaniPilkarzeIdPilkarz")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArchiwalneKlubyIdKlub", "ArchwilaniPilkarzeIdPilkarz");

                    b.HasIndex("ArchwilaniPilkarzeIdPilkarz");

                    b.ToTable("KlubPilkarz");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pilkarz", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Klub", "Klub")
                        .WithMany("ObecniPilkarze")
                        .HasForeignKey("IdKlubu")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pracownik", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Zarzad", "Zarzad")
                        .WithMany("Pracownicy")
                        .HasForeignKey("IdZarzadu")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Zarzad");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Statystyka", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Pilkarz", "Pilkarz")
                        .WithMany("Statystyki")
                        .HasForeignKey("IdPilkarz")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Pilkarz");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Zarzad", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Klub", "Klub")
                        .WithOne("Zarzad")
                        .HasForeignKey("FootballClubLibrary.Models.Zarzad", "IdKlubu")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("KlubPilkarz", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Klub", null)
                        .WithMany()
                        .HasForeignKey("ArchiwalneKlubyIdKlub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballClubLibrary.Models.Pilkarz", null)
                        .WithMany()
                        .HasForeignKey("ArchwilaniPilkarzeIdPilkarz")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Klub", b =>
                {
                    b.Navigation("ObecniPilkarze");

                    b.Navigation("Zarzad");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pilkarz", b =>
                {
                    b.Navigation("Statystyki");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Zarzad", b =>
                {
                    b.Navigation("Pracownicy");
                });
#pragma warning restore 612, 618
        }
    }
}
