// <auto-generated />
using System;
using FootballClubLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballClubLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230623180123_Migracja")]
    partial class Migracja
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballClubLibrary.Models.Klub", b =>
                {
                    b.Property<Guid>("IdKlub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nazwa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Stadion")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Trofea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKlub");

                    b.ToTable("Kluby");

                    b.HasData(
                        new
                        {
                            IdKlub = new Guid("5b76ebdf-12a5-45b9-9412-d8044fbbccab"),
                            Nazwa = "Real Madryt",
                            Stadion = "Estadio Santiago Bernabéu",
                            Trofea = "Liga Mistrzów (13 razy), Primera División (34 razy), Puchar Króla (19 razy), Superpuchar Hiszpanii (11 razy)"
                        },
                        new
                        {
                            IdKlub = new Guid("646dce1f-325b-4561-80d9-80babbd0eefe"),
                            Nazwa = "FC Barcelona",
                            Stadion = "Camp Nou",
                            Trofea = "Liga Mistrzów (5 razy), Primera División (26 razy), Puchar Króla (31 razy), Superpuchar Hiszpanii (13 razy)"
                        },
                        new
                        {
                            IdKlub = new Guid("f9334e88-98aa-469c-92b8-aec5fc192dde"),
                            Nazwa = "Juventus",
                            Stadion = "Allianz Stadium",
                            Trofea = "Liga Mistrzów (2 razy), Serie A (36 razy), Puchar Włoch (14 razy), Superpuchar Włoch (9 razy)"
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pilkarz", b =>
                {
                    b.Property<Guid>("IdPilkarz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKlubu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Pozycja")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Wiek")
                        .HasColumnType("int");

                    b.Property<decimal>("Wynagrodzenie")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPilkarz");

                    b.HasIndex("IdKlubu");

                    b.ToTable("Pilkarze");

                    b.HasData(
                        new
                        {
                            IdPilkarz = new Guid("62a77b69-8739-4a14-a898-8d1de84ccb24"),
                            IdKlubu = new Guid("5b76ebdf-12a5-45b9-9412-d8044fbbccab"),
                            Imie = "Thibaut",
                            Nazwisko = "Courtois",
                            Pozycja = "Bramkarz",
                            Wiek = 29,
                            Wynagrodzenie = 350000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("698cc8cc-caad-4515-ba3b-9aa383896940"),
                            IdKlubu = new Guid("5b76ebdf-12a5-45b9-9412-d8044fbbccab"),
                            Imie = "Dani",
                            Nazwisko = "Carvajal",
                            Pozycja = "Obrońca",
                            Wiek = 29,
                            Wynagrodzenie = 250000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("85294532-4fc8-4985-ad83-f6cb9e3b3ffc"),
                            IdKlubu = new Guid("5b76ebdf-12a5-45b9-9412-d8044fbbccab"),
                            Imie = "Raphael",
                            Nazwisko = "Varane",
                            Pozycja = "Obrońca",
                            Wiek = 28,
                            Wynagrodzenie = 300000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("63544162-323b-4417-ba17-45636c0f8b92"),
                            IdKlubu = new Guid("5b76ebdf-12a5-45b9-9412-d8044fbbccab"),
                            Imie = "Eder",
                            Nazwisko = "Militao",
                            Pozycja = "Obrońca",
                            Wiek = 23,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("275310a0-8b4e-404c-8c1b-c843910de78d"),
                            IdKlubu = new Guid("5b76ebdf-12a5-45b9-9412-d8044fbbccab"),
                            Imie = "Ferland",
                            Nazwisko = "Mendy",
                            Pozycja = "Obrońca",
                            Wiek = 26,
                            Wynagrodzenie = 220000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("57fc888f-31e2-4b2d-a977-1097e2ba8d08"),
                            IdKlubu = new Guid("5b76ebdf-12a5-45b9-9412-d8044fbbccab"),
                            Imie = "Carlos Henrique",
                            Nazwisko = "Casimiro",
                            Pozycja = "Pomocnik",
                            Wiek = 29,
                            Wynagrodzenie = 280000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("7b35fc65-2935-4cd0-9487-2ee84cf9d107"),
                            IdKlubu = new Guid("5b76ebdf-12a5-45b9-9412-d8044fbbccab"),
                            Imie = "Toni",
                            Nazwisko = "Kroos",
                            Pozycja = "Pomocnik",
                            Wiek = 31,
                            Wynagrodzenie = 320000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("a283f0b2-1547-4d10-8b78-943ef3771eb8"),
                            IdKlubu = new Guid("5b76ebdf-12a5-45b9-9412-d8044fbbccab"),
                            Imie = "Luka",
                            Nazwisko = "Modrić",
                            Pozycja = "Pomocnik",
                            Wiek = 35,
                            Wynagrodzenie = 350000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("eaf2f672-0ece-4935-9222-b0f5a2adbd34"),
                            IdKlubu = new Guid("5b76ebdf-12a5-45b9-9412-d8044fbbccab"),
                            Imie = "Marco",
                            Nazwisko = "Asensio",
                            Pozycja = "Pomocnik",
                            Wiek = 25,
                            Wynagrodzenie = 240000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("be454e0b-f322-442c-86f0-bcb1829ffe6f"),
                            IdKlubu = new Guid("5b76ebdf-12a5-45b9-9412-d8044fbbccab"),
                            Imie = "Karim",
                            Nazwisko = "Benzema",
                            Pozycja = "Napastnik",
                            Wiek = 33,
                            Wynagrodzenie = 450000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("85527111-dc5e-4fd2-8cfd-9253e860d954"),
                            IdKlubu = new Guid("5b76ebdf-12a5-45b9-9412-d8044fbbccab"),
                            Imie = "Vinicius",
                            Nazwisko = "Junior",
                            Pozycja = "Napastnik",
                            Wiek = 21,
                            Wynagrodzenie = 180000m
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pracownik", b =>
                {
                    b.Property<Guid>("IdPracownik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdZarzadu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imie")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nazwisko")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PESEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wiek")
                        .HasColumnType("int");

                    b.Property<string>("WykonywanaFunkcja")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Wynagrodzenie")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPracownik");

                    b.HasIndex("IdZarzadu");

                    b.ToTable("Pracownicy");

                    b.HasData(
                        new
                        {
                            IdPracownik = new Guid("76c5bff9-4e79-4432-b5d9-596710b72ade"),
                            IdZarzadu = new Guid("c5e4e7c6-0a0c-41ad-9a1c-5f718c456dcb"),
                            Imie = "Fiorentino",
                            Nazwisko = "Perez",
                            PESEL = "12345600101",
                            Wiek = 77,
                            WykonywanaFunkcja = "Prezes",
                            Wynagrodzenie = 420000m
                        },
                        new
                        {
                            IdPracownik = new Guid("0f9bc5d8-3d00-41fb-b76d-1a5d6584099c"),
                            IdZarzadu = new Guid("c5e4e7c6-0a0c-41ad-9a1c-5f718c456dcb"),
                            Imie = "Carlo",
                            Nazwisko = "Ancelotti",
                            PESEL = "23456700202",
                            Wiek = 64,
                            WykonywanaFunkcja = "Trener",
                            Wynagrodzenie = 350000m
                        },
                        new
                        {
                            IdPracownik = new Guid("ee0c6375-26ed-4543-855f-ddcab060d092"),
                            IdZarzadu = new Guid("c5e4e7c6-0a0c-41ad-9a1c-5f718c456dcb"),
                            Imie = "Davide",
                            Nazwisko = "Ancelotti",
                            PESEL = "34567800303",
                            Wiek = 33,
                            WykonywanaFunkcja = "Asystent trenera",
                            Wynagrodzenie = 300000m
                        },
                        new
                        {
                            IdPracownik = new Guid("0a1414ce-4804-4b3d-a0aa-c20260209223"),
                            IdZarzadu = new Guid("c5e4e7c6-0a0c-41ad-9a1c-5f718c456dcb"),
                            Imie = "Luis",
                            Nazwisko = "Llopis",
                            PESEL = "45678900404",
                            Wiek = 58,
                            WykonywanaFunkcja = "Trener Bramkarzy",
                            Wynagrodzenie = 150000m
                        },
                        new
                        {
                            IdPracownik = new Guid("09015678-73fc-430c-afb8-50738f146010"),
                            IdZarzadu = new Guid("c5e4e7c6-0a0c-41ad-9a1c-5f718c456dcb"),
                            Imie = "Javier",
                            Nazwisko = "Mallo",
                            PESEL = "56789000505",
                            Wiek = 46,
                            WykonywanaFunkcja = "Trener przygotowania fizycznego",
                            Wynagrodzenie = 1250000m
                        },
                        new
                        {
                            IdPracownik = new Guid("114669e3-dfdd-41ef-afd6-3e15bab7e315"),
                            IdZarzadu = new Guid("c5e4e7c6-0a0c-41ad-9a1c-5f718c456dcb"),
                            Imie = "Antonio",
                            Nazwisko = "Pintus",
                            PESEL = "67890100606",
                            Wiek = 60,
                            WykonywanaFunkcja = "Trener przygotowania fizycznego",
                            Wynagrodzenie = 125000m
                        },
                        new
                        {
                            IdPracownik = new Guid("9bf2bf34-ca52-48dd-ab1d-08bdb0dc2da9"),
                            IdZarzadu = new Guid("c5e4e7c6-0a0c-41ad-9a1c-5f718c456dcb"),
                            Imie = "Simone",
                            Nazwisko = "Montanaro",
                            PESEL = "78901200707",
                            Wiek = 51,
                            WykonywanaFunkcja = "Trener analityk",
                            Wynagrodzenie = 140000m
                        },
                        new
                        {
                            IdPracownik = new Guid("78f5630b-0028-4874-8adb-e31c8599e486"),
                            IdZarzadu = new Guid("c5e4e7c6-0a0c-41ad-9a1c-5f718c456dcb"),
                            Imie = "Iker",
                            Nazwisko = "Casillas",
                            PESEL = "89012300808",
                            Wiek = 42,
                            WykonywanaFunkcja = "Wice-prezes zarządu",
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPracownik = new Guid("76c3bdb3-0f8b-4e79-ae4f-489d4e439917"),
                            IdZarzadu = new Guid("c5e4e7c6-0a0c-41ad-9a1c-5f718c456dcb"),
                            Imie = "Juni",
                            Nazwisko = "Calafat",
                            PESEL = "90123400909",
                            Wiek = 50,
                            WykonywanaFunkcja = "Szef skautingu",
                            Wynagrodzenie = 200000m
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Statystyka", b =>
                {
                    b.Property<Guid>("IdStatystyka")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Asysty")
                        .HasColumnType("int");

                    b.Property<int>("CzerwoneKartki")
                        .HasColumnType("int");

                    b.Property<int>("Gole")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdPilkarz")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mecz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ocena")
                        .HasColumnType("float");

                    b.Property<double>("PrzebiegnietyDystans")
                        .HasColumnType("float");

                    b.Property<int>("ZolteKartki")
                        .HasColumnType("int");

                    b.HasKey("IdStatystyka");

                    b.HasIndex("IdPilkarz");

                    b.ToTable("Statystki");

                    b.HasData(
                        new
                        {
                            IdStatystyka = new Guid("6e0b6ff0-1be6-405c-a23e-f948bdbef114"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("be454e0b-f322-442c-86f0-bcb1829ffe6f"),
                            Mecz = "Real Madrid vs Atletico Madrid",
                            Ocena = 8.0999999999999996,
                            PrzebiegnietyDystans = 9.1999999999999993,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("f479321b-a961-4ce9-a51f-344fbb360be4"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("a283f0b2-1547-4d10-8b78-943ef3771eb8"),
                            Mecz = "Real Madrid vs FC Barcelona",
                            Ocena = 7.5,
                            PrzebiegnietyDystans = 8.4000000000000004,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("937288c6-e6d1-4fce-9e83-ec787532a6ab"),
                            Asysty = 2,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("eaf2f672-0ece-4935-9222-b0f5a2adbd34"),
                            Mecz = "Real Madrid vs PSG",
                            Ocena = 8.6999999999999993,
                            PrzebiegnietyDystans = 9.8000000000000007,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("15ad7e67-170d-4c98-bf10-dc18c35e0027"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("275310a0-8b4e-404c-8c1b-c843910de78d"),
                            Mecz = "Real Madrid vs Liverpool",
                            Ocena = 7.9000000000000004,
                            PrzebiegnietyDystans = 8.5999999999999996,
                            ZolteKartki = 2
                        },
                        new
                        {
                            IdStatystyka = new Guid("fd79226b-183a-4212-a19b-f27c4847a2c4"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("57fc888f-31e2-4b2d-a977-1097e2ba8d08"),
                            Mecz = "Real Madrid vs Bayern Monachium",
                            Ocena = 7.2999999999999998,
                            PrzebiegnietyDystans = 8.1999999999999993,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("09070374-b8ec-431a-a405-2085cd8e0fdf"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("be454e0b-f322-442c-86f0-bcb1829ffe6f"),
                            Mecz = "Real Madrid vs Sevilla",
                            Ocena = 8.0,
                            PrzebiegnietyDystans = 9.0999999999999996,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("850b45ef-7c21-4242-ac5f-32932ad573d3"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 2,
                            IdPilkarz = new Guid("a283f0b2-1547-4d10-8b78-943ef3771eb8"),
                            Mecz = "Real Madrid vs Valencia",
                            Ocena = 8.1999999999999993,
                            PrzebiegnietyDystans = 8.5,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("257819e5-ae76-4963-a6b6-6cd6b9a18487"),
                            Asysty = 2,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("eaf2f672-0ece-4935-9222-b0f5a2adbd34"),
                            Mecz = "Real Madrid vs Atalanta",
                            Ocena = 8.5,
                            PrzebiegnietyDystans = 9.6999999999999993,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("20728071-3b87-44d6-8ba1-1ece97cf5f41"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("275310a0-8b4e-404c-8c1b-c843910de78d"),
                            Mecz = "Real Madrid vs Chelsea",
                            Ocena = 7.7999999999999998,
                            PrzebiegnietyDystans = 8.9000000000000004,
                            ZolteKartki = 2
                        },
                        new
                        {
                            IdStatystyka = new Guid("fb56cc42-a0db-41db-912c-406acbcf2f59"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("57fc888f-31e2-4b2d-a977-1097e2ba8d08"),
                            Mecz = "Real Madrid vs Juventus",
                            Ocena = 7.5999999999999996,
                            PrzebiegnietyDystans = 8.3000000000000007,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("b3a978c8-e3c2-4f46-aa94-b74fab871fb9"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("be454e0b-f322-442c-86f0-bcb1829ffe6f"),
                            Mecz = "Real Madrid vs AC Milan",
                            Ocena = 8.3000000000000007,
                            PrzebiegnietyDystans = 9.4000000000000004,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("326fe5c0-787f-4415-9a06-1d97252255dc"),
                            Asysty = 2,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("a283f0b2-1547-4d10-8b78-943ef3771eb8"),
                            Mecz = "Real Madrid vs Manchester City",
                            Ocena = 8.5999999999999996,
                            PrzebiegnietyDystans = 9.5999999999999996,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("6b0e06e9-bed6-473b-9f69-5ae1b548bc02"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("eaf2f672-0ece-4935-9222-b0f5a2adbd34"),
                            Mecz = "Real Madrid vs Arsenal",
                            Ocena = 7.9000000000000004,
                            PrzebiegnietyDystans = 8.6999999999999993,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("ffb1e724-ecc3-4b3a-8de7-730c0ee56566"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("275310a0-8b4e-404c-8c1b-c843910de78d"),
                            Mecz = "Real Madrid vs Tottenham",
                            Ocena = 7.7000000000000002,
                            PrzebiegnietyDystans = 8.8000000000000007,
                            ZolteKartki = 2
                        },
                        new
                        {
                            IdStatystyka = new Guid("33c249b2-87b9-4727-8a01-3c2db4164797"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("57fc888f-31e2-4b2d-a977-1097e2ba8d08"),
                            Mecz = "Real Madrid vs Inter Milan",
                            Ocena = 7.7999999999999998,
                            PrzebiegnietyDystans = 8.5,
                            ZolteKartki = 1
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Zarzad", b =>
                {
                    b.Property<Guid>("IdZarzad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Budzet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cele")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdKlubu")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdZarzad");

                    b.HasIndex("IdKlubu")
                        .IsUnique()
                        .HasFilter("[IdKlubu] IS NOT NULL");

                    b.ToTable("Zarzady");

                    b.HasData(
                        new
                        {
                            IdZarzad = new Guid("c5e4e7c6-0a0c-41ad-9a1c-5f718c456dcb"),
                            Budzet = 2500000m,
                            Cele = "Liga Mistrzów, Superpuchar Hiszpanii, Naprawa murawy, Renowacja krzesełek, Nowy młody napastnik",
                            IdKlubu = new Guid("5b76ebdf-12a5-45b9-9412-d8044fbbccab")
                        },
                        new
                        {
                            IdZarzad = new Guid("e3db1031-4b3e-41e7-91f3-c90420ffb1c8"),
                            Budzet = 2000000m,
                            Cele = "Liga Mistrzów, Primera División, Puchar Króla, Odnowienie akademii młodzieżowej, Wzmocnienie składu",
                            IdKlubu = new Guid("646dce1f-325b-4561-80d9-80babbd0eefe")
                        },
                        new
                        {
                            IdZarzad = new Guid("244124f6-bcbe-4196-8598-d9b14cadde5b"),
                            Budzet = 1800000m,
                            Cele = "Liga Mistrzów, Serie A, Puchar Włoch, Akademia młodzieżowa, Rozwój infrastruktury",
                            IdKlubu = new Guid("f9334e88-98aa-469c-92b8-aec5fc192dde")
                        });
                });

            modelBuilder.Entity("KlubPilkarz", b =>
                {
                    b.Property<Guid>("ArchiwalneKlubyIdKlub")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArchwilaniPilkarzeIdPilkarz")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArchiwalneKlubyIdKlub", "ArchwilaniPilkarzeIdPilkarz");

                    b.HasIndex("ArchwilaniPilkarzeIdPilkarz");

                    b.ToTable("KlubPilkarz");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pilkarz", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Klub", "Klub")
                        .WithMany("ObecniPilkarze")
                        .HasForeignKey("IdKlubu")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pracownik", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Zarzad", "Zarzad")
                        .WithMany("Pracownicy")
                        .HasForeignKey("IdZarzadu")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Zarzad");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Statystyka", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Pilkarz", "Pilkarz")
                        .WithMany("Statystyki")
                        .HasForeignKey("IdPilkarz")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Pilkarz");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Zarzad", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Klub", "Klub")
                        .WithOne("Zarzad")
                        .HasForeignKey("FootballClubLibrary.Models.Zarzad", "IdKlubu")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("KlubPilkarz", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Klub", null)
                        .WithMany()
                        .HasForeignKey("ArchiwalneKlubyIdKlub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballClubLibrary.Models.Pilkarz", null)
                        .WithMany()
                        .HasForeignKey("ArchwilaniPilkarzeIdPilkarz")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Klub", b =>
                {
                    b.Navigation("ObecniPilkarze");

                    b.Navigation("Zarzad");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pilkarz", b =>
                {
                    b.Navigation("Statystyki");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Zarzad", b =>
                {
                    b.Navigation("Pracownicy");
                });
#pragma warning restore 612, 618
        }
    }
}
