// <auto-generated />
using System;
using FootballClubLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballClubLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230731104439_Migracja")]
    partial class Migracja
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballClubLibrary.Models.Klub", b =>
                {
                    b.Property<Guid>("IdKlub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nazwa")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Stadion")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Trofea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKlub");

                    b.ToTable("Kluby");

                    b.HasData(
                        new
                        {
                            IdKlub = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Nazwa = "Real Madryt",
                            Stadion = "Estadio Santiago Bernabéu",
                            Trofea = "Liga Mistrzów (13 razy), Primera División (34 razy), Puchar Króla (19 razy), Superpuchar Hiszpanii (11 razy)"
                        },
                        new
                        {
                            IdKlub = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Nazwa = "Real Madrid Castilla CF",
                            Stadion = "Estadio Alfredo Di Stéfano",
                            Trofea = "Segunda División (1 raz), Segunda División B (5 razy), Tercera División (6 razy), Trofeo Teide (3 razy), Torneo de San Ginés (2 razy)"
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pilkarz", b =>
                {
                    b.Property<Guid>("IdPilkarz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKlubu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Pozycja")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Wiek")
                        .HasColumnType("int");

                    b.Property<decimal>("Wynagrodzenie")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPilkarz");

                    b.HasIndex("IdKlubu");

                    b.ToTable("Pilkarze");

                    b.HasData(
                        new
                        {
                            IdPilkarz = new Guid("d0fecd05-3bdc-4288-80b5-c6df1c9ece4d"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Thibaut",
                            Nazwisko = "Courtois",
                            Pozycja = "Bramkarz",
                            Wiek = 29,
                            Wynagrodzenie = 350000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("dcb78893-ffa9-4edd-a8b7-d7d3d3ce03dc"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Andrij",
                            Nazwisko = "Łunin",
                            Pozycja = "Bramkarz",
                            Wiek = 24,
                            Wynagrodzenie = 150000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("373ba1e1-4d2d-46f9-b676-c68a7b2328b2"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Dani",
                            Nazwisko = "Carvajal",
                            Pozycja = "Prawy obrońca",
                            Wiek = 29,
                            Wynagrodzenie = 250000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("448d3808-308b-4cd3-9a3c-d9b890343cdb"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Eder",
                            Nazwisko = "Militao",
                            Pozycja = "Środkowy obrońca",
                            Wiek = 23,
                            Wynagrodzenie = 230000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("6b43c9b9-4319-4eef-afed-b51cdddf704d"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "David",
                            Nazwisko = "Alaba",
                            Pozycja = "Środkowy obrońca",
                            Wiek = 31,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("45384d63-037c-4dcb-b2cb-58ac49ee372e"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Nacho",
                            Nazwisko = "Fernández",
                            Pozycja = "Środkowy obrońca",
                            Wiek = 33,
                            Wynagrodzenie = 240000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("b6853ab3-8d00-4e31-8a71-575151b0a245"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Álvaro",
                            Nazwisko = "Odriozola",
                            Pozycja = "Prawy obrońca",
                            Wiek = 27,
                            Wynagrodzenie = 160000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("a9e8b71c-4890-4abf-a4fe-74aa5b993c1f"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Lucas",
                            Nazwisko = "Vázquez",
                            Pozycja = "Prawy obrońca",
                            Wiek = 32,
                            Wynagrodzenie = 265000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("ca98ab15-66ec-4899-b736-38a7868ac98e"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Fran",
                            Nazwisko = "García",
                            Pozycja = "Lewy obrońca",
                            Wiek = 23,
                            Wynagrodzenie = 170000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("08a94f13-1330-4572-a8de-70b5baba5ee1"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Antonio",
                            Nazwisko = "Rüdiger",
                            Pozycja = "Środkowy obrońca",
                            Wiek = 30,
                            Wynagrodzenie = 195000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("d6bac47b-fb29-4e0d-a3bd-eda79a3248a2"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Ferland",
                            Nazwisko = "Mendy",
                            Pozycja = "Lewy obrońca",
                            Wiek = 26,
                            Wynagrodzenie = 245000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("9abee86c-869d-48e9-9e38-b9e9416ad399"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Jude",
                            Nazwisko = "Bellingham",
                            Pozycja = "Środkowy pomocnik",
                            Wiek = 20,
                            Wynagrodzenie = 360000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("b1157463-d91d-4ee5-be62-3ba0338e179c"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Toni",
                            Nazwisko = "Kroos",
                            Pozycja = "Środkowy pomocnik",
                            Wiek = 33,
                            Wynagrodzenie = 250000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("7137ea48-1eaf-4694-a05e-d2f44db8d86b"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Luka",
                            Nazwisko = "Modrić",
                            Pozycja = "Środkowy pomocnik",
                            Wiek = 37,
                            Wynagrodzenie = 270000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("528d6659-d033-4493-8a54-19cab8c8b495"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Eduardo",
                            Nazwisko = "Camavinga",
                            Pozycja = "Środkowy pomocnik",
                            Wiek = 20,
                            Wynagrodzenie = 235000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("7d8f4687-b94e-41c8-8f56-1223a842b059"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Federico",
                            Nazwisko = "Valverde",
                            Pozycja = "Środkowy pomocnik",
                            Wiek = 25,
                            Wynagrodzenie = 255000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("0ae1a8c5-effa-45a8-a871-cb93f0f3b558"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Aurélien",
                            Nazwisko = "Tchouaméni",
                            Pozycja = "Środkowy pomocnik",
                            Wiek = 23,
                            Wynagrodzenie = 236000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("cf0c7602-19d0-4bfa-b96b-4c9312804550"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Daniel",
                            Nazwisko = "Ceballos",
                            Pozycja = "Środkowy pomocnik",
                            Wiek = 26,
                            Wynagrodzenie = 175000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("4f3d8210-c7a0-428d-924e-68b9bda84889"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Arda",
                            Nazwisko = "Güler",
                            Pozycja = "Ofensywny pomocnik",
                            Wiek = 18,
                            Wynagrodzenie = 140000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("12531077-74b6-4b6c-9e3d-dd5aa0105b6a"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Vinicius",
                            Nazwisko = "Junior",
                            Pozycja = "Lewy skrzydłowy",
                            Wiek = 21,
                            Wynagrodzenie = 420000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("cdd9b537-56e6-4434-9f4d-f4c347c6b9c7"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Rodrygo",
                            Nazwisko = "Goes",
                            Pozycja = "Prawy krzydłowy",
                            Wiek = 22,
                            Wynagrodzenie = 195000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("9ab4c31d-93bf-41a1-b4cc-89affe90047d"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Joselu",
                            Nazwisko = "Luís Sanmartín Mato",
                            Pozycja = "Środkowy napastnik",
                            Wiek = 33,
                            Wynagrodzenie = 150000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("3bca1526-848e-45bc-b015-ebe3c224a046"),
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a"),
                            Imie = "Brahim",
                            Nazwisko = "Díaz",
                            Pozycja = "Prawy skrzydłowy",
                            Wiek = 23,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("80fb75e7-e8e7-454f-83b2-565332810614"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Lucas",
                            Nazwisko = "Cañizares",
                            Pozycja = "Bramkarz",
                            Wiek = 21,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("21e93bb3-35fd-4749-b756-bf2c62a0aeab"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Mario",
                            Nazwisko = "De Luis",
                            Pozycja = "Bramkarz",
                            Wiek = 21,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("479a6a94-899e-4642-899d-d52882c9167b"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Vinicius",
                            Nazwisko = "Tobias",
                            Pozycja = "Prawy obrońca",
                            Wiek = 19,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("52e52b9b-9e3a-49e2-8bda-0fa603b433f6"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Álvaro",
                            Nazwisko = "Carrillo",
                            Pozycja = "Środkowy obrońca",
                            Wiek = 21,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("c3a3bd84-21e2-4dd0-b042-291f6ba42bd8"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Pablo",
                            Nazwisko = "Ramón",
                            Pozycja = "Środkowy obrońca",
                            Wiek = 22,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("369137df-ec0c-40f4-9de9-9bbb5ee1266b"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Lucas",
                            Nazwisko = "Alcázar",
                            Pozycja = "Środkowy obrońca",
                            Wiek = 21,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("9c58220f-1996-48d7-aa65-7ac122c19ee8"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Marvelous",
                            Nazwisko = "Garzón",
                            Pozycja = "Środkowy obrońca",
                            Wiek = 20,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("234966ff-d6c7-4bee-bef2-44c2ef59ed55"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Theo",
                            Nazwisko = "Fernández",
                            Pozycja = "Środkowy pomocnik",
                            Wiek = 21,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("d413b5e5-46a9-4465-aa12-2dafc9833a5c"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Carlos",
                            Nazwisko = "Dotor",
                            Pozycja = "Środkowy pomocnik",
                            Wiek = 22,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("b059a572-6467-4697-abc7-07ca625ad0ad"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Peter",
                            Nazwisko = "González",
                            Pozycja = "Środkowy pomocnik",
                            Wiek = 21,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("a93c40c3-c098-4fa9-80ee-5d034df07ce1"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Álvaro",
                            Nazwisko = "Martín",
                            Pozycja = "Środkowy pomocnik",
                            Wiek = 22,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("a6fec0c2-5db8-4977-b8c9-b1068306c8a7"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Takuhiro",
                            Nazwisko = "Nakai",
                            Pozycja = "Środkowy pomocnik",
                            Wiek = 19,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("ec1214f0-b7cf-4de7-b454-942167fa24e5"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Álvaro",
                            Nazwisko = "Leiva",
                            Pozycja = "Środkowy pomocnik",
                            Wiek = 18,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("5ea30d5c-fe56-4870-a29f-f07a4d129704"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Javier",
                            Nazwisko = "Villar",
                            Pozycja = "Środkowy pomocnik",
                            Wiek = 20,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("f7c43299-8814-407d-8c8a-5742f91c180a"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Óscar",
                            Nazwisko = "Aranda",
                            Pozycja = "Środkowy pomocnik",
                            Wiek = 21,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("d87dd3fe-dab3-40f9-bc3e-c946016b50e0"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Rafael",
                            Nazwisko = "Llorente",
                            Pozycja = "Środkowy pomocnik",
                            Wiek = 20,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("12828e66-4716-4003-9bd2-61160f39341f"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Mario",
                            Nazwisko = "Martín",
                            Pozycja = "Środkowy pomocnik",
                            Wiek = 19,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("ef1d8aff-a581-4438-a01b-83ba29ce27dd"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Sergio",
                            Nazwisko = "Arribas",
                            Pozycja = "Środkowy pomocnik",
                            Wiek = 21,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("8ce35861-751a-4e3f-a291-c7107806c6e7"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Noel",
                            Nazwisko = "López",
                            Pozycja = "Środkowy napastnik",
                            Wiek = 20,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("dc57befc-1bdb-4a9f-a83e-b1f5cdadf060"),
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431"),
                            Imie = "Iker",
                            Nazwisko = "Bravo",
                            Pozycja = "Środkowy napastnik",
                            Wiek = 18,
                            Wynagrodzenie = 200000m
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pracownik", b =>
                {
                    b.Property<Guid>("IdPracownik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdZarzadu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imie")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nazwisko")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PESEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wiek")
                        .HasColumnType("int");

                    b.Property<string>("WykonywanaFunkcja")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Wynagrodzenie")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPracownik");

                    b.HasIndex("IdZarzadu");

                    b.ToTable("Pracownicy");

                    b.HasData(
                        new
                        {
                            IdPracownik = new Guid("dd7fd399-303f-460e-bf8f-a77464e8ac5a"),
                            IdZarzadu = new Guid("d8d6c710-69ae-4693-b117-26ce0655a5d4"),
                            Imie = "Fiorentino",
                            Nazwisko = "Perez",
                            PESEL = "12345600101",
                            Wiek = 77,
                            WykonywanaFunkcja = "Prezes",
                            Wynagrodzenie = 420000m
                        },
                        new
                        {
                            IdPracownik = new Guid("6bfb6f89-0c81-40a1-b679-17514e6e5db3"),
                            IdZarzadu = new Guid("d8d6c710-69ae-4693-b117-26ce0655a5d4"),
                            Imie = "Carlo",
                            Nazwisko = "Ancelotti",
                            PESEL = "23456700202",
                            Wiek = 64,
                            WykonywanaFunkcja = "Trener",
                            Wynagrodzenie = 350000m
                        },
                        new
                        {
                            IdPracownik = new Guid("8e61238a-fadf-4867-a129-d5aee07a2de8"),
                            IdZarzadu = new Guid("d8d6c710-69ae-4693-b117-26ce0655a5d4"),
                            Imie = "Davide",
                            Nazwisko = "Ancelotti",
                            PESEL = "34567800303",
                            Wiek = 33,
                            WykonywanaFunkcja = "Asystent trenera",
                            Wynagrodzenie = 300000m
                        },
                        new
                        {
                            IdPracownik = new Guid("0fc84b64-5d4e-40df-b6e7-588e211402c6"),
                            IdZarzadu = new Guid("d8d6c710-69ae-4693-b117-26ce0655a5d4"),
                            Imie = "Antonio",
                            Nazwisko = "Pintus",
                            PESEL = "67890100606",
                            Wiek = 60,
                            WykonywanaFunkcja = "Szef od przygotowania fizycznego",
                            Wynagrodzenie = 125000m
                        },
                        new
                        {
                            IdPracownik = new Guid("6bcbe20c-d0b6-4b9f-8880-7020b545cc9d"),
                            IdZarzadu = new Guid("d8d6c710-69ae-4693-b117-26ce0655a5d4"),
                            Imie = "Francesco",
                            Nazwisko = "Mauri",
                            PESEL = "87890400406",
                            Wiek = 34,
                            WykonywanaFunkcja = "Fizjoterapeuta",
                            Wynagrodzenie = 125000m
                        },
                        new
                        {
                            IdPracownik = new Guid("6c655272-c116-4481-a969-14b2c9cd9eb3"),
                            IdZarzadu = new Guid("d8d6c710-69ae-4693-b117-26ce0655a5d4"),
                            Imie = "Simone",
                            Nazwisko = "Montanaro",
                            PESEL = "78901200707",
                            Wiek = 51,
                            WykonywanaFunkcja = "Trener analityk",
                            Wynagrodzenie = 140000m
                        },
                        new
                        {
                            IdPracownik = new Guid("10f86f2d-a19e-4fc4-a743-08a74f10e910"),
                            IdZarzadu = new Guid("d8d6c710-69ae-4693-b117-26ce0655a5d4"),
                            Imie = "Mino",
                            Nazwisko = "Fulco",
                            PESEL = "88501220767",
                            Wiek = 51,
                            WykonywanaFunkcja = "Dietetyk",
                            Wynagrodzenie = 140000m
                        },
                        new
                        {
                            IdPracownik = new Guid("c971ed33-9ffc-4f6c-9ca7-a9e61c4be2fc"),
                            IdZarzadu = new Guid("3d5b4638-64f5-487e-8e2a-96605beca028"),
                            Imie = "Raúl",
                            Nazwisko = "González",
                            PESEL = "70631490286",
                            Wiek = 46,
                            WykonywanaFunkcja = "Trener",
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPracownik = new Guid("006e8e2d-caec-4fdc-9d30-ac989f1af296"),
                            IdZarzadu = new Guid("3d5b4638-64f5-487e-8e2a-96605beca028"),
                            Imie = "Alberto",
                            Nazwisko = "Garrido",
                            PESEL = "45098763201",
                            Wiek = 47,
                            WykonywanaFunkcja = "Asystent trenera",
                            Wynagrodzenie = 140000m
                        },
                        new
                        {
                            IdPracownik = new Guid("6fd39058-e486-4872-b435-51378a32bb7c"),
                            IdZarzadu = new Guid("3d5b4638-64f5-487e-8e2a-96605beca028"),
                            Imie = "Nacho",
                            Nazwisko = "S. García",
                            PESEL = "83456789021",
                            Wiek = 46,
                            WykonywanaFunkcja = "Trener przygotowania fizycznego",
                            Wynagrodzenie = 90000m
                        },
                        new
                        {
                            IdPracownik = new Guid("7f59c79b-a1b5-4e58-954b-4a7e48632c5d"),
                            IdZarzadu = new Guid("3d5b4638-64f5-487e-8e2a-96605beca028"),
                            Imie = "Víctor",
                            Nazwisko = "P. Hernández",
                            PESEL = "79806543210",
                            Wiek = 45,
                            WykonywanaFunkcja = "Trener przygotowania fizycznego",
                            Wynagrodzenie = 90000m
                        },
                        new
                        {
                            IdPracownik = new Guid("fdd0b169-57b7-4dbe-92c1-4c5dc90a19c0"),
                            IdZarzadu = new Guid("3d5b4638-64f5-487e-8e2a-96605beca028"),
                            Imie = "Mario",
                            Nazwisko = "Soria Amor",
                            PESEL = "70123450789",
                            Wiek = 53,
                            WykonywanaFunkcja = "Trener bramkarzy",
                            Wynagrodzenie = 100000m
                        },
                        new
                        {
                            IdPracownik = new Guid("4527f08f-da5b-4e0c-ab04-563520ba3e57"),
                            IdZarzadu = new Guid("3d5b4638-64f5-487e-8e2a-96605beca028"),
                            Imie = "Javier",
                            Nazwisko = "de Tomás Maroto",
                            PESEL = "84501230769",
                            Wiek = 46,
                            WykonywanaFunkcja = "Fizjoterapeuta",
                            Wynagrodzenie = 75000m
                        },
                        new
                        {
                            IdPracownik = new Guid("d05ef1f3-45fb-469d-b618-ccccea7b0d10"),
                            IdZarzadu = new Guid("3d5b4638-64f5-487e-8e2a-96605beca028"),
                            Imie = "Tirso",
                            Nazwisko = "Álvarez",
                            PESEL = "89765432109",
                            Wiek = 40,
                            WykonywanaFunkcja = "Fizjoterapeuta",
                            Wynagrodzenie = 75000m
                        },
                        new
                        {
                            IdPracownik = new Guid("b58e90bd-d68a-4b55-b57a-257d3e28d181"),
                            IdZarzadu = new Guid("3d5b4638-64f5-487e-8e2a-96605beca028"),
                            Imie = "Álvaro",
                            Nazwisko = "Tavira",
                            PESEL = "71234567890",
                            Wiek = 35,
                            WykonywanaFunkcja = "Fizjoterapeuta",
                            Wynagrodzenie = 75000m
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Statystyka", b =>
                {
                    b.Property<Guid>("IdStatystyka")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Asysty")
                        .HasColumnType("int");

                    b.Property<int>("CzerwoneKartki")
                        .HasColumnType("int");

                    b.Property<int>("Gole")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdPilkarz")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mecz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ocena")
                        .HasColumnType("float");

                    b.Property<double>("PrzebiegnietyDystans")
                        .HasColumnType("float");

                    b.Property<int>("ZolteKartki")
                        .HasColumnType("int");

                    b.HasKey("IdStatystyka");

                    b.HasIndex("IdPilkarz");

                    b.ToTable("Statystki");

                    b.HasData(
                        new
                        {
                            IdStatystyka = new Guid("39297dad-5f17-455a-bee6-a7ce570bc34c"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("d0fecd05-3bdc-4288-80b5-c6df1c9ece4d"),
                            Mecz = "Real Madrid vs Liverpool",
                            Ocena = 8.8000000000000007,
                            PrzebiegnietyDystans = 0.80000000000000004,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("773b4e5a-f207-471e-be5c-d5094c22fcb4"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("dcb78893-ffa9-4edd-a8b7-d7d3d3ce03dc"),
                            Mecz = "Real Madrid vs Juventus",
                            Ocena = 8.1999999999999993,
                            PrzebiegnietyDystans = 0.40000000000000002,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("857a7c5e-3778-4501-b8f7-0ef0cdf3bb80"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("373ba1e1-4d2d-46f9-b676-c68a7b2328b2"),
                            Mecz = "Real Madrid vs Atletico Madrid",
                            Ocena = 8.5,
                            PrzebiegnietyDystans = 10.5,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("a85d1bf5-d0e3-44b6-89a0-afd29170e014"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("448d3808-308b-4cd3-9a3c-d9b890343cdb"),
                            Mecz = "Real Madrid vs Bayern Munich",
                            Ocena = 8.9000000000000004,
                            PrzebiegnietyDystans = 9.6999999999999993,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("00b92a85-fe82-401f-bbe3-e83aab9d4b01"),
                            Asysty = 2,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("6b43c9b9-4319-4eef-afed-b51cdddf704d"),
                            Mecz = "Real Madrid vs Paris Saint-Germain",
                            Ocena = 9.0999999999999996,
                            PrzebiegnietyDystans = 10.1,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("2bedbc0f-1966-48ab-825b-e4c5cf0ca9fd"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("7137ea48-1eaf-4694-a05e-d2f44db8d86b"),
                            Mecz = "Real Madrid vs FC Barcelona",
                            Ocena = 7.5,
                            PrzebiegnietyDystans = 8.4000000000000004,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("de3e80cc-b5c7-467f-9a5f-e474e9a2e07e"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("d6bac47b-fb29-4e0d-a3bd-eda79a3248a2"),
                            Mecz = "Real Madrid vs Liverpool",
                            Ocena = 7.9000000000000004,
                            PrzebiegnietyDystans = 8.5999999999999996,
                            ZolteKartki = 2
                        },
                        new
                        {
                            IdStatystyka = new Guid("b1c0c7c6-2a32-42db-b9cb-6b23873a2a9b"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 2,
                            IdPilkarz = new Guid("7137ea48-1eaf-4694-a05e-d2f44db8d86b"),
                            Mecz = "Real Madrid vs Valencia",
                            Ocena = 8.1999999999999993,
                            PrzebiegnietyDystans = 8.5,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("2a0b018b-cc1a-4919-a5d4-ef1c0d21b6c2"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("d6bac47b-fb29-4e0d-a3bd-eda79a3248a2"),
                            Mecz = "Real Madrid vs Chelsea",
                            Ocena = 7.7999999999999998,
                            PrzebiegnietyDystans = 8.9000000000000004,
                            ZolteKartki = 2
                        },
                        new
                        {
                            IdStatystyka = new Guid("cdd4a260-0e21-4299-ac2c-d2a628556297"),
                            Asysty = 2,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("7137ea48-1eaf-4694-a05e-d2f44db8d86b"),
                            Mecz = "Real Madrid vs Manchester City",
                            Ocena = 8.5999999999999996,
                            PrzebiegnietyDystans = 9.5999999999999996,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("8321714e-4805-46e2-aa1b-c681c1c5babf"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("d6bac47b-fb29-4e0d-a3bd-eda79a3248a2"),
                            Mecz = "Real Madrid vs Tottenham",
                            Ocena = 7.7000000000000002,
                            PrzebiegnietyDystans = 8.8000000000000007,
                            ZolteKartki = 2
                        },
                        new
                        {
                            IdStatystyka = new Guid("2163889d-1253-413b-8ece-35be30daca55"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("9ab4c31d-93bf-41a1-b4cc-89affe90047d"),
                            Mecz = "Real Madrid vs Napoli",
                            Ocena = 7.5999999999999996,
                            PrzebiegnietyDystans = 8.1999999999999993,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("269ecb10-4782-4fc2-8153-4b20eed2bb2b"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("3bca1526-848e-45bc-b015-ebe3c224a046"),
                            Mecz = "Real Madrid vs Ajax",
                            Ocena = 8.4000000000000004,
                            PrzebiegnietyDystans = 9.3000000000000007,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("40b1f5ac-15da-4879-b663-bfb704010af0"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("9abee86c-869d-48e9-9e38-b9e9416ad399"),
                            Mecz = "Real Madrid vs RB Leipzig",
                            Ocena = 8.9000000000000004,
                            PrzebiegnietyDystans = 9.9000000000000004,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("9b376466-0fdc-4656-9dff-a4a0972dc94d"),
                            Asysty = 3,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("b1157463-d91d-4ee5-be62-3ba0338e179c"),
                            Mecz = "Real Madrid vs Sevilla",
                            Ocena = 9.0999999999999996,
                            PrzebiegnietyDystans = 10.699999999999999,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("340817fe-e202-4e17-bacc-491f4dc43f3e"),
                            Asysty = 0,
                            CzerwoneKartki = 1,
                            Gole = 0,
                            IdPilkarz = new Guid("4f3d8210-c7a0-428d-924e-68b9bda84889"),
                            Mecz = "Real Madrid vs Galatasaray",
                            Ocena = 6.5,
                            PrzebiegnietyDystans = 7.7999999999999998,
                            ZolteKartki = 2
                        },
                        new
                        {
                            IdStatystyka = new Guid("6685a1c4-66cd-466b-a80b-add1cc7aeb8c"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("479a6a94-899e-4642-899d-d52882c9167b"),
                            Mecz = "Real Madrid Castilla vs Atletico Madrid B",
                            Ocena = 8.4000000000000004,
                            PrzebiegnietyDystans = 8.0999999999999996,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("c02fd773-9d11-4fa0-898b-9aa8868ee4da"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("52e52b9b-9e3a-49e2-8bda-0fa603b433f6"),
                            Mecz = "Real Madrid Castilla vs Sevilla Atletico",
                            Ocena = 7.9000000000000004,
                            PrzebiegnietyDystans = 7.5,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("40e3c95b-ff57-45e5-85a5-d5f81100add7"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("c3a3bd84-21e2-4dd0-b042-291f6ba42bd8"),
                            Mecz = "Real Madrid Castilla vs Real Betis B",
                            Ocena = 8.0999999999999996,
                            PrzebiegnietyDystans = 7.7999999999999998,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("715df8b3-8b63-46b5-8a7f-ffb1d265731c"),
                            Asysty = 2,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("369137df-ec0c-40f4-9de9-9bbb5ee1266b"),
                            Mecz = "Real Madrid Castilla vs Getafe B",
                            Ocena = 8.5,
                            PrzebiegnietyDystans = 8.5,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("2e3a75c5-6f1b-4499-8ae5-88f9ba36fe0e"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("9c58220f-1996-48d7-aa65-7ac122c19ee8"),
                            Mecz = "Real Madrid Castilla vs Rayo Vallecano B",
                            Ocena = 7.7000000000000002,
                            PrzebiegnietyDystans = 7.4000000000000004,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("85bb3d31-3560-43ef-baf1-eddf080dd02d"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("234966ff-d6c7-4bee-bef2-44c2ef59ed55"),
                            Mecz = "Real Madrid Castilla vs Alcorcón B",
                            Ocena = 8.3000000000000007,
                            PrzebiegnietyDystans = 7.9000000000000004,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("e832bd2f-757a-4b2f-ad35-b8568bbc09a7"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("d413b5e5-46a9-4465-aa12-2dafc9833a5c"),
                            Mecz = "Real Madrid Castilla vs Huesca B",
                            Ocena = 8.0,
                            PrzebiegnietyDystans = 7.5999999999999996,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("22ebc38a-4e8e-45e2-b67f-612a997e1d13"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("b059a572-6467-4697-abc7-07ca625ad0ad"),
                            Mecz = "Real Madrid Castilla vs CD Badajoz",
                            Ocena = 8.5999999999999996,
                            PrzebiegnietyDystans = 8.1999999999999993,
                            ZolteKartki = 1
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Zarzad", b =>
                {
                    b.Property<Guid>("IdZarzad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Budzet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cele")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdKlubu")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdZarzad");

                    b.HasIndex("IdKlubu")
                        .IsUnique()
                        .HasFilter("[IdKlubu] IS NOT NULL");

                    b.ToTable("Zarzady");

                    b.HasData(
                        new
                        {
                            IdZarzad = new Guid("d8d6c710-69ae-4693-b117-26ce0655a5d4"),
                            Budzet = 2500000m,
                            Cele = "Liga Mistrzów, Superpuchar Hiszpanii, Naprawa murawy, Renowacja krzesełek, Nowy młody napastnik",
                            IdKlubu = new Guid("06118cdc-d28d-4e9a-86ad-1fa14418505a")
                        },
                        new
                        {
                            IdZarzad = new Guid("3d5b4638-64f5-487e-8e2a-96605beca028"),
                            Budzet = 1250000m,
                            Cele = "Awans do Segunda División",
                            IdKlubu = new Guid("fa5f539a-fa36-4a2d-9acd-bf571bf79431")
                        });
                });

            modelBuilder.Entity("KlubPilkarz", b =>
                {
                    b.Property<Guid>("ArchiwalneKlubyIdKlub")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArchiwalniPilkarzeIdPilkarz")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArchiwalneKlubyIdKlub", "ArchiwalniPilkarzeIdPilkarz");

                    b.HasIndex("ArchiwalniPilkarzeIdPilkarz");

                    b.ToTable("KlubPilkarz");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pilkarz", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Klub", "Klub")
                        .WithMany("ObecniPilkarze")
                        .HasForeignKey("IdKlubu")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pracownik", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Zarzad", "Zarzad")
                        .WithMany("Pracownicy")
                        .HasForeignKey("IdZarzadu")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Zarzad");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Statystyka", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Pilkarz", "Pilkarz")
                        .WithMany("Statystyki")
                        .HasForeignKey("IdPilkarz")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Pilkarz");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Zarzad", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Klub", "Klub")
                        .WithOne("Zarzad")
                        .HasForeignKey("FootballClubLibrary.Models.Zarzad", "IdKlubu")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("KlubPilkarz", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Klub", null)
                        .WithMany()
                        .HasForeignKey("ArchiwalneKlubyIdKlub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballClubLibrary.Models.Pilkarz", null)
                        .WithMany()
                        .HasForeignKey("ArchiwalniPilkarzeIdPilkarz")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Klub", b =>
                {
                    b.Navigation("ObecniPilkarze");

                    b.Navigation("Zarzad");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pilkarz", b =>
                {
                    b.Navigation("Statystyki");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Zarzad", b =>
                {
                    b.Navigation("Pracownicy");
                });
#pragma warning restore 612, 618
        }
    }
}
