// <auto-generated />
using System;
using FootballClubLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballClubLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballClubLibrary.Models.Klub", b =>
                {
                    b.Property<Guid>("IdKlub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nazwa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Stadion")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Trofea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKlub");

                    b.ToTable("Kluby");

                    b.HasData(
                        new
                        {
                            IdKlub = new Guid("92e4cb05-cce9-449d-8e39-fba252c47ba1"),
                            Nazwa = "Real Madryt",
                            Stadion = "Estadio Santiago Bernabéu",
                            Trofea = "Liga Mistrzów (13 razy), Primera División (34 razy), Puchar Króla (19 razy), Superpuchar Hiszpanii (11 razy)"
                        },
                        new
                        {
                            IdKlub = new Guid("60b76cbe-81e7-49a9-b0d0-7032296a7e69"),
                            Nazwa = "FC Barcelona",
                            Stadion = "Camp Nou",
                            Trofea = "Liga Mistrzów (5 razy), Primera División (26 razy), Puchar Króla (31 razy), Superpuchar Hiszpanii (13 razy)"
                        },
                        new
                        {
                            IdKlub = new Guid("5128b21a-e6b9-4aef-8c1e-307a6fe57980"),
                            Nazwa = "Juventus",
                            Stadion = "Allianz Stadium",
                            Trofea = "Liga Mistrzów (2 razy), Serie A (36 razy), Puchar Włoch (14 razy), Superpuchar Włoch (9 razy)"
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pilkarz", b =>
                {
                    b.Property<Guid>("IdPilkarz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKlubu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Pozycja")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Wiek")
                        .HasColumnType("int");

                    b.Property<decimal>("Wynagrodzenie")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPilkarz");

                    b.HasIndex("IdKlubu");

                    b.ToTable("Pilkarze");

                    b.HasData(
                        new
                        {
                            IdPilkarz = new Guid("2dc9b501-b8e8-406d-b1dd-a2d75c09bb6c"),
                            IdKlubu = new Guid("92e4cb05-cce9-449d-8e39-fba252c47ba1"),
                            Imie = "Thibaut",
                            Nazwisko = "Courtois",
                            Pozycja = "Bramkarz",
                            Wiek = 29,
                            Wynagrodzenie = 350000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("4b4c693d-0d59-4095-88a4-d5e90b9edb94"),
                            IdKlubu = new Guid("92e4cb05-cce9-449d-8e39-fba252c47ba1"),
                            Imie = "Dani",
                            Nazwisko = "Carvajal",
                            Pozycja = "Obrońca",
                            Wiek = 29,
                            Wynagrodzenie = 250000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("2bfc2dab-fa67-464b-9a67-2accef09a8e6"),
                            IdKlubu = new Guid("92e4cb05-cce9-449d-8e39-fba252c47ba1"),
                            Imie = "Raphael",
                            Nazwisko = "Varane",
                            Pozycja = "Obrońca",
                            Wiek = 28,
                            Wynagrodzenie = 300000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("5480053a-38f1-416b-9e5d-3cca81a3ec3e"),
                            IdKlubu = new Guid("92e4cb05-cce9-449d-8e39-fba252c47ba1"),
                            Imie = "Eder",
                            Nazwisko = "Militao",
                            Pozycja = "Obrońca",
                            Wiek = 23,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("a38cbad7-8cce-472e-8501-4c56197461dd"),
                            IdKlubu = new Guid("92e4cb05-cce9-449d-8e39-fba252c47ba1"),
                            Imie = "Ferland",
                            Nazwisko = "Mendy",
                            Pozycja = "Obrońca",
                            Wiek = 26,
                            Wynagrodzenie = 220000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("18abe966-c138-442d-af8a-066f8ed8ff82"),
                            IdKlubu = new Guid("92e4cb05-cce9-449d-8e39-fba252c47ba1"),
                            Imie = "Carlos Henrique",
                            Nazwisko = "Casimiro",
                            Pozycja = "Pomocnik",
                            Wiek = 29,
                            Wynagrodzenie = 280000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("dcc261ab-9650-484f-b246-68185e9b1fec"),
                            IdKlubu = new Guid("92e4cb05-cce9-449d-8e39-fba252c47ba1"),
                            Imie = "Toni",
                            Nazwisko = "Kroos",
                            Pozycja = "Pomocnik",
                            Wiek = 31,
                            Wynagrodzenie = 320000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("913390be-a78f-4359-b86e-fcadf9e04f4b"),
                            IdKlubu = new Guid("92e4cb05-cce9-449d-8e39-fba252c47ba1"),
                            Imie = "Luka",
                            Nazwisko = "Modrić",
                            Pozycja = "Pomocnik",
                            Wiek = 35,
                            Wynagrodzenie = 350000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("43eb151c-6670-4c49-b7a4-c6fa596f9672"),
                            IdKlubu = new Guid("92e4cb05-cce9-449d-8e39-fba252c47ba1"),
                            Imie = "Marco",
                            Nazwisko = "Asensio",
                            Pozycja = "Pomocnik",
                            Wiek = 25,
                            Wynagrodzenie = 240000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("dacee609-350b-4063-9ab0-3b45e5d7f56c"),
                            IdKlubu = new Guid("92e4cb05-cce9-449d-8e39-fba252c47ba1"),
                            Imie = "Karim",
                            Nazwisko = "Benzema",
                            Pozycja = "Napastnik",
                            Wiek = 33,
                            Wynagrodzenie = 450000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("92078c5b-86f8-462a-8e44-17e394929fd0"),
                            IdKlubu = new Guid("92e4cb05-cce9-449d-8e39-fba252c47ba1"),
                            Imie = "Vinicius",
                            Nazwisko = "Junior",
                            Pozycja = "Napastnik",
                            Wiek = 21,
                            Wynagrodzenie = 180000m
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pracownik", b =>
                {
                    b.Property<Guid>("IdPracownik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdZarzadu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imie")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nazwisko")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PESEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wiek")
                        .HasColumnType("int");

                    b.Property<string>("WykonywanaFunkcja")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Wynagrodzenie")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPracownik");

                    b.HasIndex("IdZarzadu");

                    b.ToTable("Pracownicy");

                    b.HasData(
                        new
                        {
                            IdPracownik = new Guid("7d6a550a-583e-4a18-a1bf-14422268dc18"),
                            IdZarzadu = new Guid("99a3bae0-86f7-4a8d-ae5d-cb890d86e41b"),
                            Imie = "Fiorentino",
                            Nazwisko = "Perez",
                            PESEL = "12345600101",
                            Wiek = 77,
                            WykonywanaFunkcja = "Prezes",
                            Wynagrodzenie = 420000m
                        },
                        new
                        {
                            IdPracownik = new Guid("b079260d-4783-4a45-814a-091523e3dc06"),
                            IdZarzadu = new Guid("99a3bae0-86f7-4a8d-ae5d-cb890d86e41b"),
                            Imie = "Carlo",
                            Nazwisko = "Ancelotti",
                            PESEL = "23456700202",
                            Wiek = 64,
                            WykonywanaFunkcja = "Trener",
                            Wynagrodzenie = 350000m
                        },
                        new
                        {
                            IdPracownik = new Guid("a07af027-d1ec-41ac-a25f-8776df952f1b"),
                            IdZarzadu = new Guid("99a3bae0-86f7-4a8d-ae5d-cb890d86e41b"),
                            Imie = "Davide",
                            Nazwisko = "Ancelotti",
                            PESEL = "34567800303",
                            Wiek = 33,
                            WykonywanaFunkcja = "Asystent trenera",
                            Wynagrodzenie = 300000m
                        },
                        new
                        {
                            IdPracownik = new Guid("720d475b-d529-4159-b218-7ed97f479cf8"),
                            IdZarzadu = new Guid("99a3bae0-86f7-4a8d-ae5d-cb890d86e41b"),
                            Imie = "Luis",
                            Nazwisko = "Llopis",
                            PESEL = "45678900404",
                            Wiek = 58,
                            WykonywanaFunkcja = "Trener Bramkarzy",
                            Wynagrodzenie = 150000m
                        },
                        new
                        {
                            IdPracownik = new Guid("cc2f7e66-f2c1-4724-8bb9-3e6ffa67681a"),
                            IdZarzadu = new Guid("99a3bae0-86f7-4a8d-ae5d-cb890d86e41b"),
                            Imie = "Javier",
                            Nazwisko = "Mallo",
                            PESEL = "56789000505",
                            Wiek = 46,
                            WykonywanaFunkcja = "Trener przygotowania fizycznego",
                            Wynagrodzenie = 1250000m
                        },
                        new
                        {
                            IdPracownik = new Guid("bf4e794b-5997-43a3-8b20-5b2517305bd5"),
                            IdZarzadu = new Guid("99a3bae0-86f7-4a8d-ae5d-cb890d86e41b"),
                            Imie = "Antonio",
                            Nazwisko = "Pintus",
                            PESEL = "67890100606",
                            Wiek = 60,
                            WykonywanaFunkcja = "Trener przygotowania fizycznego",
                            Wynagrodzenie = 125000m
                        },
                        new
                        {
                            IdPracownik = new Guid("c575ff03-5339-486e-b94e-f2a20df4ccb1"),
                            IdZarzadu = new Guid("99a3bae0-86f7-4a8d-ae5d-cb890d86e41b"),
                            Imie = "Simone",
                            Nazwisko = "Montanaro",
                            PESEL = "78901200707",
                            Wiek = 51,
                            WykonywanaFunkcja = "Trener analityk",
                            Wynagrodzenie = 140000m
                        },
                        new
                        {
                            IdPracownik = new Guid("c49f0b4f-8a6b-4bd5-b3c8-97987e40a6dc"),
                            IdZarzadu = new Guid("99a3bae0-86f7-4a8d-ae5d-cb890d86e41b"),
                            Imie = "Iker",
                            Nazwisko = "Casillas",
                            PESEL = "89012300808",
                            Wiek = 42,
                            WykonywanaFunkcja = "Wice-prezes zarządu",
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPracownik = new Guid("3362e435-2147-4e11-a0a7-2031a40c72ea"),
                            IdZarzadu = new Guid("99a3bae0-86f7-4a8d-ae5d-cb890d86e41b"),
                            Imie = "Juni",
                            Nazwisko = "Calafat",
                            PESEL = "90123400909",
                            Wiek = 50,
                            WykonywanaFunkcja = "Szef skautingu",
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPracownik = new Guid("11ba2f3f-b9d6-4229-aab2-4897f495fdc8"),
                            Imie = "Mateusz",
                            Nazwisko = "Kostyra",
                            PESEL = "780124500909",
                            Wiek = 23,
                            WykonywanaFunkcja = "",
                            Wynagrodzenie = 10000000m
                        },
                        new
                        {
                            IdPracownik = new Guid("29103e4b-c8ef-478b-bd5f-724707b4add2"),
                            Imie = "Stanisław",
                            Nazwisko = "Kluczewski",
                            PESEL = "45423402949",
                            Wiek = 23,
                            WykonywanaFunkcja = "",
                            Wynagrodzenie = 5000000m
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Statystyka", b =>
                {
                    b.Property<Guid>("IdStatystyka")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Asysty")
                        .HasColumnType("int");

                    b.Property<int>("CzerwoneKartki")
                        .HasColumnType("int");

                    b.Property<int>("Gole")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdPilkarz")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mecz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ocena")
                        .HasColumnType("float");

                    b.Property<double>("PrzebiegnietyDystans")
                        .HasColumnType("float");

                    b.Property<int>("ZolteKartki")
                        .HasColumnType("int");

                    b.HasKey("IdStatystyka");

                    b.HasIndex("IdPilkarz");

                    b.ToTable("Statystki");

                    b.HasData(
                        new
                        {
                            IdStatystyka = new Guid("6021c88f-7ba4-4c93-b73b-7fbf4385bead"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("dacee609-350b-4063-9ab0-3b45e5d7f56c"),
                            Mecz = "Real Madrid vs Atletico Madrid",
                            Ocena = 8.0999999999999996,
                            PrzebiegnietyDystans = 9.1999999999999993,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("99af6f3c-e95b-47d4-9e6d-b4311a6e2068"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("913390be-a78f-4359-b86e-fcadf9e04f4b"),
                            Mecz = "Real Madrid vs FC Barcelona",
                            Ocena = 7.5,
                            PrzebiegnietyDystans = 8.4000000000000004,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("9eb65a17-d04f-42c7-88f9-390f9570333e"),
                            Asysty = 2,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("43eb151c-6670-4c49-b7a4-c6fa596f9672"),
                            Mecz = "Real Madrid vs PSG",
                            Ocena = 8.6999999999999993,
                            PrzebiegnietyDystans = 9.8000000000000007,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("900e4775-ca1f-4716-8ea2-8dad5f291324"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("a38cbad7-8cce-472e-8501-4c56197461dd"),
                            Mecz = "Real Madrid vs Liverpool",
                            Ocena = 7.9000000000000004,
                            PrzebiegnietyDystans = 8.5999999999999996,
                            ZolteKartki = 2
                        },
                        new
                        {
                            IdStatystyka = new Guid("c76437a8-ec60-499f-979f-b40d4b5548c4"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("18abe966-c138-442d-af8a-066f8ed8ff82"),
                            Mecz = "Real Madrid vs Bayern Monachium",
                            Ocena = 7.2999999999999998,
                            PrzebiegnietyDystans = 8.1999999999999993,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("f77f4547-aa4f-411e-95ce-19c8978dec5c"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("dacee609-350b-4063-9ab0-3b45e5d7f56c"),
                            Mecz = "Real Madrid vs Sevilla",
                            Ocena = 8.0,
                            PrzebiegnietyDystans = 9.0999999999999996,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("2a104f8c-7ded-4f48-8b7d-d591d0169349"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 2,
                            IdPilkarz = new Guid("913390be-a78f-4359-b86e-fcadf9e04f4b"),
                            Mecz = "Real Madrid vs Valencia",
                            Ocena = 8.1999999999999993,
                            PrzebiegnietyDystans = 8.5,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("1f5d6e69-68de-401a-93b5-45482061c5c3"),
                            Asysty = 2,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("43eb151c-6670-4c49-b7a4-c6fa596f9672"),
                            Mecz = "Real Madrid vs Atalanta",
                            Ocena = 8.5,
                            PrzebiegnietyDystans = 9.6999999999999993,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("946475d5-6713-4f0f-b2e9-57b0cac3b3ef"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("a38cbad7-8cce-472e-8501-4c56197461dd"),
                            Mecz = "Real Madrid vs Chelsea",
                            Ocena = 7.7999999999999998,
                            PrzebiegnietyDystans = 8.9000000000000004,
                            ZolteKartki = 2
                        },
                        new
                        {
                            IdStatystyka = new Guid("62e3c6c2-2e58-48ae-a00c-5ae840e1a2eb"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("18abe966-c138-442d-af8a-066f8ed8ff82"),
                            Mecz = "Real Madrid vs Juventus",
                            Ocena = 7.5999999999999996,
                            PrzebiegnietyDystans = 8.3000000000000007,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("91aa9200-21ba-4716-a7a5-1c393e28c044"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("dacee609-350b-4063-9ab0-3b45e5d7f56c"),
                            Mecz = "Real Madrid vs AC Milan",
                            Ocena = 8.3000000000000007,
                            PrzebiegnietyDystans = 9.4000000000000004,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("0e29c631-890d-4386-b83a-a2201c34c4e3"),
                            Asysty = 2,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("913390be-a78f-4359-b86e-fcadf9e04f4b"),
                            Mecz = "Real Madrid vs Manchester City",
                            Ocena = 8.5999999999999996,
                            PrzebiegnietyDystans = 9.5999999999999996,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("3bb929e5-ade1-421d-8d43-0f970bd3c34b"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("43eb151c-6670-4c49-b7a4-c6fa596f9672"),
                            Mecz = "Real Madrid vs Arsenal",
                            Ocena = 7.9000000000000004,
                            PrzebiegnietyDystans = 8.6999999999999993,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("2b7fcb6d-730a-44ec-8090-3c2fe14bb3f7"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("a38cbad7-8cce-472e-8501-4c56197461dd"),
                            Mecz = "Real Madrid vs Tottenham",
                            Ocena = 7.7000000000000002,
                            PrzebiegnietyDystans = 8.8000000000000007,
                            ZolteKartki = 2
                        },
                        new
                        {
                            IdStatystyka = new Guid("9705e34a-38ac-44fa-9a04-3ad5bbc585d0"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("18abe966-c138-442d-af8a-066f8ed8ff82"),
                            Mecz = "Real Madrid vs Inter Milan",
                            Ocena = 7.7999999999999998,
                            PrzebiegnietyDystans = 8.5,
                            ZolteKartki = 1
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Zarzad", b =>
                {
                    b.Property<Guid>("IdZarzad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Budzet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cele")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdKlubu")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdZarzad");

                    b.HasIndex("IdKlubu")
                        .IsUnique()
                        .HasFilter("[IdKlubu] IS NOT NULL");

                    b.ToTable("Zarzady");

                    b.HasData(
                        new
                        {
                            IdZarzad = new Guid("99a3bae0-86f7-4a8d-ae5d-cb890d86e41b"),
                            Budzet = 2500000m,
                            Cele = "Liga Mistrzów, Superpuchar Hiszpanii, Naprawa murawy, Renowacja krzesełek, Nowy młody napastnik",
                            IdKlubu = new Guid("92e4cb05-cce9-449d-8e39-fba252c47ba1")
                        },
                        new
                        {
                            IdZarzad = new Guid("77b3ccb5-4c02-4725-bb10-43872e315398"),
                            Budzet = 2000000m,
                            Cele = "Liga Mistrzów, Primera División, Puchar Króla, Odnowienie akademii młodzieżowej, Wzmocnienie składu",
                            IdKlubu = new Guid("60b76cbe-81e7-49a9-b0d0-7032296a7e69")
                        },
                        new
                        {
                            IdZarzad = new Guid("08713cb3-6e15-4b34-b0cd-8a7a95060a00"),
                            Budzet = 1800000m,
                            Cele = "Liga Mistrzów, Serie A, Puchar Włoch, Akademia młodzieżowa, Rozwój infrastruktury",
                            IdKlubu = new Guid("5128b21a-e6b9-4aef-8c1e-307a6fe57980")
                        });
                });

            modelBuilder.Entity("KlubPilkarz", b =>
                {
                    b.Property<Guid>("ArchiwalneKlubyIdKlub")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArchwilaniPilkarzeIdPilkarz")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArchiwalneKlubyIdKlub", "ArchwilaniPilkarzeIdPilkarz");

                    b.HasIndex("ArchwilaniPilkarzeIdPilkarz");

                    b.ToTable("KlubPilkarz");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pilkarz", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Klub", "Klub")
                        .WithMany("ObecniPilkarze")
                        .HasForeignKey("IdKlubu")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pracownik", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Zarzad", "Zarzad")
                        .WithMany("Pracownicy")
                        .HasForeignKey("IdZarzadu")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Zarzad");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Statystyka", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Pilkarz", "Pilkarz")
                        .WithMany("Statystyki")
                        .HasForeignKey("IdPilkarz")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Pilkarz");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Zarzad", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Klub", "Klub")
                        .WithOne("Zarzad")
                        .HasForeignKey("FootballClubLibrary.Models.Zarzad", "IdKlubu")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("KlubPilkarz", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Klub", null)
                        .WithMany()
                        .HasForeignKey("ArchiwalneKlubyIdKlub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballClubLibrary.Models.Pilkarz", null)
                        .WithMany()
                        .HasForeignKey("ArchwilaniPilkarzeIdPilkarz")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Klub", b =>
                {
                    b.Navigation("ObecniPilkarze");

                    b.Navigation("Zarzad");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pilkarz", b =>
                {
                    b.Navigation("Statystyki");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Zarzad", b =>
                {
                    b.Navigation("Pracownicy");
                });
#pragma warning restore 612, 618
        }
    }
}
