// <auto-generated />
using System;
using FootballClubLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballClubLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballClubLibrary.Models.Klub", b =>
                {
                    b.Property<Guid>("IdKlub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nazwa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Stadion")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Trofea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKlub");

                    b.ToTable("Kluby");

                    b.HasData(
                        new
                        {
                            IdKlub = new Guid("93aef9fc-6263-4bd6-8d03-25f783298d4c"),
                            Nazwa = "Real Madryt",
                            Stadion = "Estadio Santiago Bernabéu",
                            Trofea = "Liga Mistrzów (13 razy), Primera División (34 razy), Puchar Króla (19 razy), Superpuchar Hiszpanii (11 razy)"
                        },
                        new
                        {
                            IdKlub = new Guid("3bad4552-ed17-45ad-b7e1-efdc4bacca9a"),
                            Nazwa = "FC Barcelona",
                            Stadion = "Camp Nou",
                            Trofea = "Liga Mistrzów (5 razy), Primera División (26 razy), Puchar Króla (31 razy), Superpuchar Hiszpanii (13 razy)"
                        },
                        new
                        {
                            IdKlub = new Guid("5f719cd7-19c9-45cb-b6f0-c78882a81a23"),
                            Nazwa = "Juventus",
                            Stadion = "Allianz Stadium",
                            Trofea = "Liga Mistrzów (2 razy), Serie A (36 razy), Puchar Włoch (14 razy), Superpuchar Włoch (9 razy)"
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pilkarz", b =>
                {
                    b.Property<Guid>("IdPilkarz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKlubu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Pozycja")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Wiek")
                        .HasColumnType("int");

                    b.Property<decimal>("Wynagrodzenie")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPilkarz");

                    b.HasIndex("IdKlubu");

                    b.ToTable("Pilkarze");

                    b.HasData(
                        new
                        {
                            IdPilkarz = new Guid("79d4458a-909d-418b-aa28-c718e39362dd"),
                            IdKlubu = new Guid("93aef9fc-6263-4bd6-8d03-25f783298d4c"),
                            Imie = "Thibaut",
                            Nazwisko = "Courtois",
                            Pozycja = "Bramkarz",
                            Wiek = 29,
                            Wynagrodzenie = 350000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("c99d07b2-b064-4f99-927e-c75892e89322"),
                            IdKlubu = new Guid("93aef9fc-6263-4bd6-8d03-25f783298d4c"),
                            Imie = "Dani",
                            Nazwisko = "Carvajal",
                            Pozycja = "Obrońca",
                            Wiek = 29,
                            Wynagrodzenie = 250000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("94dc432f-2df7-4569-ad14-247149913d3c"),
                            IdKlubu = new Guid("93aef9fc-6263-4bd6-8d03-25f783298d4c"),
                            Imie = "Raphael",
                            Nazwisko = "Varane",
                            Pozycja = "Obrońca",
                            Wiek = 28,
                            Wynagrodzenie = 300000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("ef335694-b7aa-40ce-b9d7-f7450cf03fe7"),
                            IdKlubu = new Guid("93aef9fc-6263-4bd6-8d03-25f783298d4c"),
                            Imie = "Eder",
                            Nazwisko = "Militao",
                            Pozycja = "Obrońca",
                            Wiek = 23,
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("7df92ca1-32ff-41ad-8de4-5572a16f169b"),
                            IdKlubu = new Guid("93aef9fc-6263-4bd6-8d03-25f783298d4c"),
                            Imie = "Ferland",
                            Nazwisko = "Mendy",
                            Pozycja = "Obrońca",
                            Wiek = 26,
                            Wynagrodzenie = 220000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("243c318a-ef37-4cc4-922f-32fe35877921"),
                            IdKlubu = new Guid("93aef9fc-6263-4bd6-8d03-25f783298d4c"),
                            Imie = "Carlos Henrique",
                            Nazwisko = "Casimiro",
                            Pozycja = "Pomocnik",
                            Wiek = 29,
                            Wynagrodzenie = 280000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("e4d51f0a-bc05-4386-8f80-f7c1ea2cc06c"),
                            IdKlubu = new Guid("93aef9fc-6263-4bd6-8d03-25f783298d4c"),
                            Imie = "Toni",
                            Nazwisko = "Kroos",
                            Pozycja = "Pomocnik",
                            Wiek = 31,
                            Wynagrodzenie = 320000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("23fad9ad-3f30-476d-9385-61beade997e4"),
                            IdKlubu = new Guid("93aef9fc-6263-4bd6-8d03-25f783298d4c"),
                            Imie = "Luka",
                            Nazwisko = "Modrić",
                            Pozycja = "Pomocnik",
                            Wiek = 35,
                            Wynagrodzenie = 350000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("66dc3b6a-6457-4713-b803-f0c3037570fd"),
                            IdKlubu = new Guid("93aef9fc-6263-4bd6-8d03-25f783298d4c"),
                            Imie = "Marco",
                            Nazwisko = "Asensio",
                            Pozycja = "Pomocnik",
                            Wiek = 25,
                            Wynagrodzenie = 240000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("4b36ff41-13a3-4863-921e-848f68200f93"),
                            IdKlubu = new Guid("93aef9fc-6263-4bd6-8d03-25f783298d4c"),
                            Imie = "Karim",
                            Nazwisko = "Benzema",
                            Pozycja = "Napastnik",
                            Wiek = 33,
                            Wynagrodzenie = 450000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("5e569d43-8919-4133-ba4d-6c809ff257a7"),
                            IdKlubu = new Guid("93aef9fc-6263-4bd6-8d03-25f783298d4c"),
                            Imie = "Vinicius",
                            Nazwisko = "Junior",
                            Pozycja = "Napastnik",
                            Wiek = 21,
                            Wynagrodzenie = 180000m
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pracownik", b =>
                {
                    b.Property<Guid>("IdPracownik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdZarzadu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imie")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nazwisko")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PESEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wiek")
                        .HasColumnType("int");

                    b.Property<string>("WykonywanaFunkcja")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Wynagrodzenie")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPracownik");

                    b.HasIndex("IdZarzadu");

                    b.ToTable("Pracownicy");

                    b.HasData(
                        new
                        {
                            IdPracownik = new Guid("ee72c56f-773a-4ec8-a78b-1133cb71f916"),
                            IdZarzadu = new Guid("937da978-a2a5-481c-9df4-5bc4db79d052"),
                            Imie = "Fiorentino",
                            Nazwisko = "Perez",
                            PESEL = "12345600101",
                            Wiek = 77,
                            WykonywanaFunkcja = "Prezes",
                            Wynagrodzenie = 420000m
                        },
                        new
                        {
                            IdPracownik = new Guid("5ee22d1c-0087-413f-a0e3-d041448dda33"),
                            IdZarzadu = new Guid("937da978-a2a5-481c-9df4-5bc4db79d052"),
                            Imie = "Carlo",
                            Nazwisko = "Ancelotti",
                            PESEL = "23456700202",
                            Wiek = 64,
                            WykonywanaFunkcja = "Trener",
                            Wynagrodzenie = 350000m
                        },
                        new
                        {
                            IdPracownik = new Guid("9e6ba0fe-5dcb-4337-840b-0b28b42e6ad1"),
                            IdZarzadu = new Guid("937da978-a2a5-481c-9df4-5bc4db79d052"),
                            Imie = "Davide",
                            Nazwisko = "Ancelotti",
                            PESEL = "34567800303",
                            Wiek = 33,
                            WykonywanaFunkcja = "Asystent trenera",
                            Wynagrodzenie = 300000m
                        },
                        new
                        {
                            IdPracownik = new Guid("fc473cd9-54ee-4258-a536-1bcd2ac44375"),
                            IdZarzadu = new Guid("937da978-a2a5-481c-9df4-5bc4db79d052"),
                            Imie = "Luis",
                            Nazwisko = "Llopis",
                            PESEL = "45678900404",
                            Wiek = 58,
                            WykonywanaFunkcja = "Trener Bramkarzy",
                            Wynagrodzenie = 150000m
                        },
                        new
                        {
                            IdPracownik = new Guid("ffccc730-c6df-4492-8653-3c3f8a1e49d0"),
                            IdZarzadu = new Guid("937da978-a2a5-481c-9df4-5bc4db79d052"),
                            Imie = "Javier",
                            Nazwisko = "Mallo",
                            PESEL = "56789000505",
                            Wiek = 46,
                            WykonywanaFunkcja = "Trener przygotowania fizycznego",
                            Wynagrodzenie = 1250000m
                        },
                        new
                        {
                            IdPracownik = new Guid("e75399cf-3349-4a04-b8f4-0b85b82893f5"),
                            IdZarzadu = new Guid("937da978-a2a5-481c-9df4-5bc4db79d052"),
                            Imie = "Antonio",
                            Nazwisko = "Pintus",
                            PESEL = "67890100606",
                            Wiek = 60,
                            WykonywanaFunkcja = "Trener przygotowania fizycznego",
                            Wynagrodzenie = 125000m
                        },
                        new
                        {
                            IdPracownik = new Guid("be8a9a05-42a9-422b-8b8f-e4f33c664f5e"),
                            IdZarzadu = new Guid("937da978-a2a5-481c-9df4-5bc4db79d052"),
                            Imie = "Simone",
                            Nazwisko = "Montanaro",
                            PESEL = "78901200707",
                            Wiek = 51,
                            WykonywanaFunkcja = "Trener analityk",
                            Wynagrodzenie = 140000m
                        },
                        new
                        {
                            IdPracownik = new Guid("452b528e-a715-4a96-a174-477234c7644b"),
                            IdZarzadu = new Guid("937da978-a2a5-481c-9df4-5bc4db79d052"),
                            Imie = "Iker",
                            Nazwisko = "Casillas",
                            PESEL = "89012300808",
                            Wiek = 42,
                            WykonywanaFunkcja = "Wice-prezes zarządu",
                            Wynagrodzenie = 200000m
                        },
                        new
                        {
                            IdPracownik = new Guid("727c0eba-84b7-486f-8d9d-31dac844f033"),
                            IdZarzadu = new Guid("937da978-a2a5-481c-9df4-5bc4db79d052"),
                            Imie = "Juni",
                            Nazwisko = "Calafat",
                            PESEL = "90123400909",
                            Wiek = 50,
                            WykonywanaFunkcja = "Szef skautingu",
                            Wynagrodzenie = 200000m
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Statystyka", b =>
                {
                    b.Property<Guid>("IdStatystyka")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Asysty")
                        .HasColumnType("int");

                    b.Property<int>("CzerwoneKartki")
                        .HasColumnType("int");

                    b.Property<int>("Gole")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdPilkarz")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mecz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ocena")
                        .HasColumnType("float");

                    b.Property<double>("PrzebiegnietyDystans")
                        .HasColumnType("float");

                    b.Property<int>("ZolteKartki")
                        .HasColumnType("int");

                    b.HasKey("IdStatystyka");

                    b.HasIndex("IdPilkarz");

                    b.ToTable("Statystki");

                    b.HasData(
                        new
                        {
                            IdStatystyka = new Guid("dbb3ebd0-6cc7-4d55-b581-c42ed90235c9"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("4b36ff41-13a3-4863-921e-848f68200f93"),
                            Mecz = "Real Madrid vs Atletico Madrid",
                            Ocena = 8.0999999999999996,
                            PrzebiegnietyDystans = 9.1999999999999993,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("4718a420-14a3-4a63-b0e7-ff1395006405"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("23fad9ad-3f30-476d-9385-61beade997e4"),
                            Mecz = "Real Madrid vs FC Barcelona",
                            Ocena = 7.5,
                            PrzebiegnietyDystans = 8.4000000000000004,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("894eabde-b0d6-420f-aeea-d30be8c20316"),
                            Asysty = 2,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("66dc3b6a-6457-4713-b803-f0c3037570fd"),
                            Mecz = "Real Madrid vs PSG",
                            Ocena = 8.6999999999999993,
                            PrzebiegnietyDystans = 9.8000000000000007,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("b2a581bf-bd39-4686-ae06-3f8ca857a67a"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("7df92ca1-32ff-41ad-8de4-5572a16f169b"),
                            Mecz = "Real Madrid vs Liverpool",
                            Ocena = 7.9000000000000004,
                            PrzebiegnietyDystans = 8.5999999999999996,
                            ZolteKartki = 2
                        },
                        new
                        {
                            IdStatystyka = new Guid("fc30d473-1f15-49e1-bffa-649ec1fefdfb"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("243c318a-ef37-4cc4-922f-32fe35877921"),
                            Mecz = "Real Madrid vs Bayern Monachium",
                            Ocena = 7.2999999999999998,
                            PrzebiegnietyDystans = 8.1999999999999993,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("b94bf4ab-751c-4ea7-8e6e-9f9ce51b4071"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("4b36ff41-13a3-4863-921e-848f68200f93"),
                            Mecz = "Real Madrid vs Sevilla",
                            Ocena = 8.0,
                            PrzebiegnietyDystans = 9.0999999999999996,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("adeeb94f-7f37-4f11-9926-c594a2827b86"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 2,
                            IdPilkarz = new Guid("23fad9ad-3f30-476d-9385-61beade997e4"),
                            Mecz = "Real Madrid vs Valencia",
                            Ocena = 8.1999999999999993,
                            PrzebiegnietyDystans = 8.5,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("8a56e3c8-5601-4faa-9a56-dfde8c813539"),
                            Asysty = 2,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("66dc3b6a-6457-4713-b803-f0c3037570fd"),
                            Mecz = "Real Madrid vs Atalanta",
                            Ocena = 8.5,
                            PrzebiegnietyDystans = 9.6999999999999993,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("4c677113-7f0f-4fea-b98b-2fd4ce40c6dc"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("7df92ca1-32ff-41ad-8de4-5572a16f169b"),
                            Mecz = "Real Madrid vs Chelsea",
                            Ocena = 7.7999999999999998,
                            PrzebiegnietyDystans = 8.9000000000000004,
                            ZolteKartki = 2
                        },
                        new
                        {
                            IdStatystyka = new Guid("c6a650e1-e02c-4c32-ba55-bbfd076ce4b6"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("243c318a-ef37-4cc4-922f-32fe35877921"),
                            Mecz = "Real Madrid vs Juventus",
                            Ocena = 7.5999999999999996,
                            PrzebiegnietyDystans = 8.3000000000000007,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("0d444821-0b14-48f1-8c44-056696203c13"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("4b36ff41-13a3-4863-921e-848f68200f93"),
                            Mecz = "Real Madrid vs AC Milan",
                            Ocena = 8.3000000000000007,
                            PrzebiegnietyDystans = 9.4000000000000004,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("a42299b8-ce76-44c5-bb4c-1450c8b42d03"),
                            Asysty = 2,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("23fad9ad-3f30-476d-9385-61beade997e4"),
                            Mecz = "Real Madrid vs Manchester City",
                            Ocena = 8.5999999999999996,
                            PrzebiegnietyDystans = 9.5999999999999996,
                            ZolteKartki = 1
                        },
                        new
                        {
                            IdStatystyka = new Guid("30191131-c5d6-4b1b-b3e1-bc26442b9075"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("66dc3b6a-6457-4713-b803-f0c3037570fd"),
                            Mecz = "Real Madrid vs Arsenal",
                            Ocena = 7.9000000000000004,
                            PrzebiegnietyDystans = 8.6999999999999993,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("eb3a31e0-f319-4058-8fda-5b65904eb439"),
                            Asysty = 1,
                            CzerwoneKartki = 0,
                            Gole = 0,
                            IdPilkarz = new Guid("7df92ca1-32ff-41ad-8de4-5572a16f169b"),
                            Mecz = "Real Madrid vs Tottenham",
                            Ocena = 7.7000000000000002,
                            PrzebiegnietyDystans = 8.8000000000000007,
                            ZolteKartki = 2
                        },
                        new
                        {
                            IdStatystyka = new Guid("8c19a1b6-7802-4e9f-91b5-10be6d847a58"),
                            Asysty = 0,
                            CzerwoneKartki = 0,
                            Gole = 1,
                            IdPilkarz = new Guid("243c318a-ef37-4cc4-922f-32fe35877921"),
                            Mecz = "Real Madrid vs Inter Milan",
                            Ocena = 7.7999999999999998,
                            PrzebiegnietyDystans = 8.5,
                            ZolteKartki = 1
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Zarzad", b =>
                {
                    b.Property<Guid>("IdZarzad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Budzet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cele")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdKlubu")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdZarzad");

                    b.HasIndex("IdKlubu")
                        .IsUnique()
                        .HasFilter("[IdKlubu] IS NOT NULL");

                    b.ToTable("Zarzady");

                    b.HasData(
                        new
                        {
                            IdZarzad = new Guid("937da978-a2a5-481c-9df4-5bc4db79d052"),
                            Budzet = 2500000m,
                            Cele = "Liga Mistrzów, Superpuchar Hiszpanii, Naprawa murawy, Renowacja krzesełek, Nowy młody napastnik",
                            IdKlubu = new Guid("93aef9fc-6263-4bd6-8d03-25f783298d4c")
                        },
                        new
                        {
                            IdZarzad = new Guid("cc967b17-a571-4c4a-82c7-9f279f25409e"),
                            Budzet = 2000000m,
                            Cele = "Liga Mistrzów, Primera División, Puchar Króla, Odnowienie akademii młodzieżowej, Wzmocnienie składu",
                            IdKlubu = new Guid("3bad4552-ed17-45ad-b7e1-efdc4bacca9a")
                        },
                        new
                        {
                            IdZarzad = new Guid("31f70c25-a087-446f-90c3-518b6f72f0cf"),
                            Budzet = 1800000m,
                            Cele = "Liga Mistrzów, Serie A, Puchar Włoch, Akademia młodzieżowa, Rozwój infrastruktury",
                            IdKlubu = new Guid("5f719cd7-19c9-45cb-b6f0-c78882a81a23")
                        });
                });

            modelBuilder.Entity("KlubPilkarz", b =>
                {
                    b.Property<Guid>("ArchiwalneKlubyIdKlub")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArchwilaniPilkarzeIdPilkarz")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArchiwalneKlubyIdKlub", "ArchwilaniPilkarzeIdPilkarz");

                    b.HasIndex("ArchwilaniPilkarzeIdPilkarz");

                    b.ToTable("KlubPilkarz");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pilkarz", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Klub", "Klub")
                        .WithMany("ObecniPilkarze")
                        .HasForeignKey("IdKlubu")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pracownik", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Zarzad", "Zarzad")
                        .WithMany("Pracownicy")
                        .HasForeignKey("IdZarzadu")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Zarzad");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Statystyka", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Pilkarz", "Pilkarz")
                        .WithMany("Statystyki")
                        .HasForeignKey("IdPilkarz")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Pilkarz");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Zarzad", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Klub", "Klub")
                        .WithOne("Zarzad")
                        .HasForeignKey("FootballClubLibrary.Models.Zarzad", "IdKlubu")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("KlubPilkarz", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Klub", null)
                        .WithMany()
                        .HasForeignKey("ArchiwalneKlubyIdKlub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballClubLibrary.Models.Pilkarz", null)
                        .WithMany()
                        .HasForeignKey("ArchwilaniPilkarzeIdPilkarz")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Klub", b =>
                {
                    b.Navigation("ObecniPilkarze");

                    b.Navigation("Zarzad");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pilkarz", b =>
                {
                    b.Navigation("Statystyki");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Zarzad", b =>
                {
                    b.Navigation("Pracownicy");
                });
#pragma warning restore 612, 618
        }
    }
}
