// <auto-generated />
using System;
using FootballClubLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballClubLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballClubLibrary.Models.Klub", b =>
                {
                    b.Property<Guid>("IdKlub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stadion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Trofea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKlub");

                    b.ToTable("Kluby");

                    b.HasData(
                        new
                        {
                            IdKlub = new Guid("d657d937-7263-4ab8-98c4-08bb6f8b994e"),
                            Nazwa = "Real Madryt",
                            Stadion = "Estadio Santiago Bernabéu",
                            Trofea = "Liga Mistrzów"
                        },
                        new
                        {
                            IdKlub = new Guid("193dbec0-d42c-4ad4-821c-a0e8f5987e38"),
                            Nazwa = "FC Barcelona",
                            Stadion = "Camp Nou",
                            Trofea = "La Liga"
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pilkarz", b =>
                {
                    b.Property<Guid>("IdPilkarz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKlubu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Pozycja")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Wiek")
                        .HasColumnType("int");

                    b.Property<decimal>("Wynagrodzenie")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPilkarz");

                    b.HasIndex("IdKlubu");

                    b.ToTable("Pilkarze");

                    b.HasData(
                        new
                        {
                            IdPilkarz = new Guid("e6bed5e7-725d-4464-aa40-742102e75fea"),
                            Imie = "Robert",
                            Nazwisko = "Lewandowski",
                            Pozycja = "Napastnik",
                            Wiek = 35,
                            Wynagrodzenie = 440000m
                        },
                        new
                        {
                            IdPilkarz = new Guid("89909247-6d01-49e3-ba77-4e08e4e7622b"),
                            Imie = "Sergio",
                            Nazwisko = "Busquets",
                            Pozycja = "Pomocnik",
                            Wiek = 34,
                            Wynagrodzenie = 350000m
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pracownik", b =>
                {
                    b.Property<Guid>("IdPracownik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdZarzadu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imie")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nazwisko")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PESEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wiek")
                        .HasColumnType("int");

                    b.Property<string>("WykonywanaFunkcja")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Wynagrodzenie")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPracownik");

                    b.HasIndex("IdZarzadu");

                    b.ToTable("Pracownicy");

                    b.HasData(
                        new
                        {
                            IdPracownik = new Guid("136d34e9-8e2a-4458-b0d7-bf590ab84111"),
                            Imie = "Fiorentino",
                            Nazwisko = "Perez",
                            PESEL = "12345678901",
                            Wiek = 77,
                            WykonywanaFunkcja = "Prezes",
                            Wynagrodzenie = 340000m
                        },
                        new
                        {
                            IdPracownik = new Guid("2d544ac5-a381-4b9c-9fde-757df2086d47"),
                            Imie = "Carlo",
                            Nazwisko = "Carlo Ancelotti",
                            PESEL = "12345600101",
                            Wiek = 63,
                            WykonywanaFunkcja = "Trener",
                            Wynagrodzenie = 340000m
                        },
                        new
                        {
                            IdPracownik = new Guid("3428fe6e-bdd3-4398-86dd-d34731ecb70a"),
                            Imie = "Joan",
                            Nazwisko = "Laporta",
                            PESEL = "12345338901",
                            Wiek = 60,
                            WykonywanaFunkcja = "Prezes",
                            Wynagrodzenie = 340000m
                        },
                        new
                        {
                            IdPracownik = new Guid("0bf71aa4-5b4e-4ff7-b809-d9ba9c6ab743"),
                            Imie = "Xavi",
                            Nazwisko = "Hernandez",
                            PESEL = "12345600101",
                            Wiek = 43,
                            WykonywanaFunkcja = "Trener",
                            Wynagrodzenie = 340000m
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Statystyka", b =>
                {
                    b.Property<Guid>("IdStatystyka")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Asysty")
                        .HasColumnType("int");

                    b.Property<int>("CzerwoneKartki")
                        .HasColumnType("int");

                    b.Property<int>("Gole")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdPilkarz")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mecz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ocena")
                        .HasColumnType("float");

                    b.Property<double>("PrzebiegnietyDystans")
                        .HasColumnType("float");

                    b.Property<int>("ZolteKartki")
                        .HasColumnType("int");

                    b.HasKey("IdStatystyka");

                    b.HasIndex("IdPilkarz");

                    b.ToTable("Statystki");

                    b.HasData(
                        new
                        {
                            IdStatystyka = new Guid("6d05db7f-cbc7-4b6c-a28b-0c9806584ec8"),
                            Asysty = 1,
                            CzerwoneKartki = 1,
                            Gole = 4,
                            Mecz = "Real Madrid vs FC Barcelona",
                            Ocena = 8.6999999999999993,
                            PrzebiegnietyDystans = 10.4,
                            ZolteKartki = 0
                        },
                        new
                        {
                            IdStatystyka = new Guid("437cc7db-3379-4c4b-84c9-ffa300b636a3"),
                            Asysty = 2,
                            CzerwoneKartki = 1,
                            Gole = 0,
                            Mecz = "FC Barcelona vs Real Madrid",
                            Ocena = 7.5,
                            PrzebiegnietyDystans = 8.4000000000000004,
                            ZolteKartki = 2
                        });
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Zarzad", b =>
                {
                    b.Property<Guid>("IdZarzad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Budzet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cele")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdKlubu")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdZarzad");

                    b.HasIndex("IdKlubu")
                        .IsUnique()
                        .HasFilter("[IdKlubu] IS NOT NULL");

                    b.ToTable("Zarzady");

                    b.HasData(
                        new
                        {
                            IdZarzad = new Guid("0421cded-5253-469c-9622-163f6b463997"),
                            Budzet = 2000m,
                            Cele = "Cel 1"
                        });
                });

            modelBuilder.Entity("KlubPilkarz", b =>
                {
                    b.Property<Guid>("ArchiwalneKlubyIdKlub")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArchwilaniPilkarzeIdPilkarz")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArchiwalneKlubyIdKlub", "ArchwilaniPilkarzeIdPilkarz");

                    b.HasIndex("ArchwilaniPilkarzeIdPilkarz");

                    b.ToTable("KlubPilkarz");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pilkarz", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Klub", "Klub")
                        .WithMany("ObecniPilkarze")
                        .HasForeignKey("IdKlubu")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pracownik", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Zarzad", "Zarzad")
                        .WithMany("Pracownicy")
                        .HasForeignKey("IdZarzadu")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Zarzad");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Statystyka", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Pilkarz", "Pilkarz")
                        .WithMany("Statystyki")
                        .HasForeignKey("IdPilkarz")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Pilkarz");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Zarzad", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Klub", "Klub")
                        .WithOne("Zarzad")
                        .HasForeignKey("FootballClubLibrary.Models.Zarzad", "IdKlubu")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("KlubPilkarz", b =>
                {
                    b.HasOne("FootballClubLibrary.Models.Klub", null)
                        .WithMany()
                        .HasForeignKey("ArchiwalneKlubyIdKlub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballClubLibrary.Models.Pilkarz", null)
                        .WithMany()
                        .HasForeignKey("ArchwilaniPilkarzeIdPilkarz")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Klub", b =>
                {
                    b.Navigation("ObecniPilkarze");

                    b.Navigation("Zarzad");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Pilkarz", b =>
                {
                    b.Navigation("Statystyki");
                });

            modelBuilder.Entity("FootballClubLibrary.Models.Zarzad", b =>
                {
                    b.Navigation("Pracownicy");
                });
#pragma warning restore 612, 618
        }
    }
}
